export const FETCH_SONGS = 'FETCH_SONGS'
export const FETCH_SONG = 'FETCH_SONG'
export const CREATE_SONG = 'CREATE_SONG'
export const EDIT_SONG = 'EDIT_SONG'
export const DELETE_SONG = 'DELETE_SONG'
export const NEW_ALERT = 'NEW_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'